### ISSUE TITLE
Add Enterprise Wifi support

### ISSUE THREAD

**Issue by invalidflaw** [khoih-prog/WiFiManager_NINA_Lite#2]
I am planning on using this in a nixie tube clock project. I would like to be able to connect my clock to the university wifi, which uses an enterprise login. Would it be possible to make a wifi configuration using WiFiNINA_Generic `beginEnterprise`?

**Comment by khoih-prog** [comment]
Hi @invalidflaw 

You certainly can use that feature

```
// Connect to WPA2 enterprise network:
// - You can optionally provide additional identity and CA cert (string) parameters:
//      WiFi.beginEnterprise(ssid, user, pass, identity, caCert)
// . if your network requires them.
status = WiFi.beginEnterprise(ssid, user, pass);
```

Have a look at [**ConnectWithWPA2Enterprise** example](examples/ConnectWithWPA2Enterprise) for more details.

Regards,

**Comment by khoih-prog** [comment]
HI @invalidflaw 

Do you like that feature included in the library or you can  modify it yourself?

If yes, you have to wait for **new version of this library as the feature is not yet supported.**

**Comment by invalidflaw** [comment]
I would like to add this feature to the library, possibly as a second wifi password type. I started an idea for it. I can take a stab at finishing it.

**Comment by khoih-prog** [comment]
Can you clarify how you connect to your U. network ?

1. WiFi.beginEnterprise(ssid, user, pass, identity, caCert)
2. WiFi.beginEnterprise(ssid, user, pass, identity)
3. WiFi.beginEnterprise(ssid, user, pass)

I now think we don't need to modify the library. Just add the **user and identity** data to the dynamic parameters, then use the information to for beginEnterprise(). That's the **beauty and versatility of dynamic parameters feature.**

![Enterprise](https://user-images.githubusercontent.com/57012152/89544956-bbabf680-d7d0-11ea-9fad-3c0a601c7788.png)



I think you can try writing the application yourself. I can hep to finish on the way.

**Comment by invalidflaw** [comment]
Thats a good idea, I would do this, however I think this will be a larger issue than I thought. Currently there may be an issue with the "eduroam" wifi connection method. I need to investigate this before I get much further.
