### ISSUE TITLE
Knowing when configuration mode is on or off

### ISSUE THREAD

**Issue by nicogou** [khoih-prog/WiFiManager_NINA_Lite#26]
### Is your feature request related to a problem? Please describe.

I would like to know if the Config Portal is on or off, so that I can change some LED display on my device. configuration_mode is private, so I can't access it.

### Describe the solution you'd like

A method to get the configuration_mode.

### Describe alternatives you've considered
Make configuration_mode public.

Thanks a lot for the great library!

**Comment by khoih-prog** [comment]
Hi @nicogou 


The new [**WiFiManager_NINA_Lite releases v1.6.3**](https://github.com/khoih-prog/WiFiManager_NINA_Lite/releases/tag/v1.6.3) has just been published. Your contribution is noted in [**Contributions and Thanks**](https://github.com/khoih-prog/WiFiManager_NINA_Lite#contributions-and-thanks)

Best Regards,

---

### Release v1.6.3

1. Add optional `CONFIG_MODE_LED` to be `ON` when in Config Portal mode. Check [Knowing when configuration mode is on or off #26](https://github.com/khoih-prog/WiFiManager_NINA_Lite/issues/26)
2. Add function `isConfigMode()` to signal system is in Config Portal mode.
---

### How to use

https://github.com/khoih-prog/WiFiManager_NINA_Lite/blob/d894548f25b50bf32fc5311bcd1e407ff8cd210e/examples/SAMD_WiFiNINA/SAMD_WiFiNINA.ino#L23-L31


https://github.com/khoih-prog/WiFiManager_NINA_Lite/blob/d894548f25b50bf32fc5311bcd1e407ff8cd210e/examples/SAMD_WiFiNINA/defines.h#L194-L211

**Comment by nicogou** [comment]
Quick and easy, thanks mate!
