### ISSUE TITLE
Integration

### ISSUE THREAD

**Issue by Herobyte** [khoih-prog/WiFiManager_NINA_Lite#27]
Hi,
(I'm Italian, sorry for my not good english).

I try this Manager, work fine, and it's easy to configure.
I have a issue for integrate it and my script, I have this script:

`#include <SPI.h>

// ----------------------------
// Additional Libraries - each one of these will need to be installed.
// ----------------------------
#include <WiFiNINA.h>
// Library for using network deatures of the official Arudino
// Wifi Boards (MKR WiFi 1010, Nano 33 IOT etc)

// Search for "nina" in the Arduino Library Manager
// https://github.com/arduino-libraries/WiFiNINA

#include <UniversalTelegramBot.h>
// Library for connecting to Telegram

// Search for "Telegram" in the Arduino Library Manager
// Install the "Universal Telegram" one by Brian Lough
// https://github.com/witnessmenow/Universal-Arduino-Telegram-Bot

#include <ArduinoJson.h>
// Library used for parsing Json from the API responses

// Search for "Arduino Json" in the Arduino Library manager
// https://github.com/bblanchon/ArduinoJson

// Telegram BOT Token (Get from Botfather)
#define BOT_TOKEN "MyToken"

// Use @myidbot (IDBot) to find out the chat ID of an individual or a group
// Also note that you need to click "start" on a bot before it can
// message you
#define chat_id "MyID"

char SSID[] = "Myssid";         // your network SSID (name)
char PASS[] = "Mypass"; // your network password

int status = WL_IDLE_STATUS;

WiFiSSLClient client;
UniversalTelegramBot bot(BOT_TOKEN, client);

void printWiFiStatus() {
  // print the SSID of the network you're attached to:
  Serial.print("SSID: ");
  Serial.println(WiFi.SSID());

  // print your board's IP address:
  IPAddress ip = WiFi.localIP();
  Serial.print("IP Address: ");
  Serial.println(ip);

  // print the received signal strength:
  long rssi = WiFi.RSSI();
  Serial.print("signal strength (RSSI):");
  Serial.print(rssi);
  Serial.println(" dBm");
}

void setup()
{
  //Initialize serial and wait for port to open:
  Serial.begin(9600); {
    // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  // Defined in thingProperties.h
  }

  // check for the WiFi module:
  if (WiFi.status() == WL_NO_MODULE) {
    Serial.println("Communication with WiFi module failed!");
    // don't continue
    while (true);
  }

  String fv = WiFi.firmwareVersion();
  if (fv < "1.0.0") {
    Serial.println("Please upgrade the firmware");
  }

  // attempt to connect to WiFi network:
  while (status != WL_CONNECTED) {
    Serial.print("Attempting to connect to SSID: ");
    Serial.println(SSID);
    // Connect to WPA/WPA2 network. Change this line if using open or WEP network:
    status = WiFi.begin(SSID, PASS);

    // wait 10 seconds for connection:
    delay(10000);
  }
  Serial.println("Connected to wifi");
  printWiFiStatus();

  pinMode (4, INPUT);
  
  bot.sendMessage(chat_id, "Connesso!", "");

}

void loop() {

  if (digitalRead(4)) {
    bot.sendMessage(chat_id, "Aperto", "");
    // Attesa tempo 8 ore per ripristino tasto
    delay(28800000);
  } else {
  }
}`

How integrate my script for connect at the selected wifi next configure the manager?

Wait your reply,
Regards,
Alessandro

**Comment by khoih-prog** [comment]
Thanks for your interests and good usage of the library.

As this is not an issue of the library, I'm closing it now and suggest that you ask for help in Arduino Forum.

I wish I had all the precious time in the world to help everybody.

Good Luck,
