### ISSUE TITLE
Won't compile for SAMD when USE_DYNAMIC_PARAMETERS set to FALSE

### ISSUE THREAD

**Issue by bizprof** [khoih-prog/WiFiManager_NINA_Lite#5]
When using the SAMD_WiFiNINA example, and setting USE_DYNAMIC_PARAMETERS to false in defines.h, the sketch won't compile. Error messages:

- error: 'NUM_MENU_ITEMS' was not declared in this scope (code lines 1350, 1363)
- error: 'myMenuItems' was not declared in this scope (code lines 1354, 1367)

There might be a simple fix through adding the conditional statements "#if USE_DYNAMIC_PARAMETERS" / "#endif" to the code in WiFiManager_NINA_Lite_SAMD.h (twice, between code lines 1347 and 1371, to exclude the 2 "for..." blocks from compiling). This fixed it for me, and the example configuration portal now works as intended. 

The same issue probably exists for the other board examples as well (which I have not tested).

Thank you very much, it's a great toolset!

**Comment by khoih-prog** [comment]
@bizprof 

Thanks for your contribution which has been noted in [**Contributions and Thanks**](https://github.com/khoih-prog/WiFiManager_NINA_Lite#contributions-and-thanks)

The new [**WiFiManager_NINA_Lite v1.1.1**](https://github.com/khoih-prog/WiFiManager_NINA_Lite/releases/tag/v1.1.1) has been published to fix the issue.

---

### Release v1.1.1

1. Fix USE_DYNAMIC_PARAMETERS bug.
